### PR TITLE
[C++] Implement Quick Sort (Pg. 160)

### PR DESCRIPTION
**Pull request by 108anup**

### CODE REVIEW

**Comment by 108anup** [comment]
What are the CI checks, what do they do, how to add them to project on github

**Comment by 108anup** [comment]
By mistake I added Quick Sort in chap 6, I have changed that in my 4th Commit

**Comment by znck** [comment]
@108anup [Add test cases](https://github.com/znck/clrs/blob/master/CONTRIBUTING.MD)

About CI [here](https://travis-ci.org/getting_started)

**Comment by 108anup** [comment]
I think the Test Cases and the Program Code should be in the same place just like in Stanford ICPC notebook, so that the viewer does not have to view test cases separately. Rather than having separate testcases folder, the test case can be inbuilt in the main function.

**Comment by znck** [comment]
Single set of tests is used to verify correctness of implementations across all languages.

Though you can put examples in comments in the same file.

**Pull request closed without merging**
